FROM python:3.11-slim

# System deps for OCR & PDF
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    tesseract-ocr poppler-utils \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Render sets $PORT
ENV PORT=10000
CMD ["gunicorn","-w","2","-k","gthread","-t","120","-b","0.0.0.0:${PORT}","app:app"]
